### ISSUE TITLE
Service.currentContext is no more usable

### ISSUE THREAD

**Issue by kesslerdev** [Hugome/moleculer-bullmq#2]
due to [huge performance impact caused by async_hooks](https://dzone.com/articles/beware-the-performance-cost-of-async-hooks-node-8) currentContext system is dropped from moleculer

cf https://github.com/moleculerjs/moleculer/issues/676#issuecomment-585793684

https://github.com/Hugome/moleculer-bullmq/blob/master/src/index.js#L81
https://github.com/Hugome/moleculer-bullmq/blob/master/src/index.js#L97

**Comment by Hugome** [comment]
I will take a look to change that (I think i will add the little "ctx" in the method parameters).
And of course the 0.14 has been released yesterday.
Thanks for the report !
